// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ojo/airdrop/v1/airdrop.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the airdrop module.
type Params struct {
	// The block at which all unclaimed AirdropAccounts will instead mint tokens
	// into the community pool. After this block, all unclaimed airdrop accounts
	// will no longer be able to be claimed.
	ExpiryBlocks uint64 `protobuf:"varint,1,opt,name=expiry_blocks,json=expiryBlocks,proto3" json:"expiry_blocks,omitempty"`
	// The percentage of the initial airdrop that users must delegate in order to
	// receive their second portion.
	// E.g., if we want to require users to stake their entire initial airdrop, this will be 1.
	DelegationRequirement *types.DecProto `protobuf:"bytes,2,opt,name=delegation_requirement,json=delegationRequirement,proto3" json:"delegation_requirement,omitempty"`
	// The multiplier for the amount of tokens users will receive once they claim their airdrop.
	// E.g., if we want users to receive an equal second half, this will be 2.
	AirdropFactor *types.DecProto `protobuf:"bytes,3,opt,name=airdrop_factor,json=airdropFactor,proto3" json:"airdrop_factor,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_295074f7d14bf8dc, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "ojo.airdrop.v1.Params")
}

func init() { proto.RegisterFile("ojo/airdrop/v1/airdrop.proto", fileDescriptor_295074f7d14bf8dc) }

var fileDescriptor_295074f7d14bf8dc = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0xe3, 0xef, 0xab, 0x3a, 0x04, 0xda, 0x21, 0x02, 0x54, 0x55, 0x60, 0x2a, 0x58, 0x2a,
	0x24, 0x6c, 0x05, 0x36, 0xc6, 0xaa, 0x42, 0x8c, 0x55, 0xc4, 0xc4, 0x12, 0x39, 0xae, 0x09, 0x4e,
	0x9b, 0x9c, 0x60, 0xbb, 0xa1, 0xbd, 0x0b, 0x2e, 0x81, 0xcb, 0xe9, 0x46, 0x47, 0x46, 0x48, 0x16,
	0x2e, 0x03, 0xe5, 0xa7, 0x74, 0x65, 0x7b, 0xf5, 0x1e, 0x3f, 0x7e, 0x74, 0x8e, 0x7d, 0x0c, 0x11,
	0x50, 0x26, 0xd5, 0x54, 0x41, 0x4a, 0x33, 0x77, 0x1b, 0x49, 0xaa, 0xc0, 0x80, 0xd3, 0x85, 0x08,
	0xc8, 0xb6, 0xca, 0xdc, 0xfe, 0x41, 0x08, 0x21, 0x54, 0x23, 0x5a, 0xa6, 0xfa, 0x55, 0x1f, 0x73,
	0xd0, 0x31, 0x68, 0x1a, 0x30, 0x2d, 0x68, 0xe6, 0x06, 0xc2, 0x30, 0x97, 0x72, 0x90, 0x49, 0x3d,
	0x3f, 0x7b, 0x47, 0x76, 0x7b, 0xc2, 0x14, 0x8b, 0xb5, 0x73, 0x6e, 0x77, 0xc4, 0x32, 0x95, 0x6a,
	0xe5, 0x07, 0x73, 0xe0, 0x33, 0xdd, 0x43, 0x03, 0x34, 0x6c, 0x79, 0xfb, 0x75, 0x39, 0xaa, 0x3a,
	0xe7, 0xde, 0x3e, 0x9a, 0x8a, 0xb9, 0x08, 0x99, 0x91, 0x90, 0xf8, 0x4a, 0x3c, 0x2f, 0xa4, 0x12,
	0xb1, 0x48, 0x4c, 0xef, 0xdf, 0x00, 0x0d, 0xf7, 0xae, 0x4e, 0x48, 0x2d, 0x24, 0xa5, 0x90, 0x34,
	0x42, 0x32, 0x16, 0x7c, 0x52, 0xea, 0xbc, 0xc3, 0x1d, 0xec, 0xed, 0x58, 0x67, 0x6c, 0x77, 0x9b,
	0x4d, 0xfc, 0x47, 0xc6, 0x0d, 0xa8, 0xde, 0xff, 0xbf, 0xfc, 0xd6, 0x69, 0xa0, 0xdb, 0x8a, 0xb9,
	0x69, 0x7d, 0xbf, 0x9d, 0xa2, 0xd1, 0xdd, 0xfa, 0x0b, 0x5b, 0xeb, 0x1c, 0xa3, 0x4d, 0x8e, 0xd1,
	0x67, 0x8e, 0xd1, 0x6b, 0x81, 0xad, 0x4d, 0x81, 0xad, 0x8f, 0x02, 0x5b, 0x0f, 0x17, 0xa1, 0x34,
	0x4f, 0x8b, 0x80, 0x70, 0x88, 0x29, 0x44, 0x70, 0x99, 0x08, 0xf3, 0x02, 0x6a, 0x56, 0x66, 0xba,
	0xfc, 0x3d, 0xb6, 0x59, 0xa5, 0x42, 0x07, 0xed, 0xea, 0x44, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xd2, 0xe1, 0x73, 0x3a, 0x88, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ExpiryBlocks != that1.ExpiryBlocks {
		return false
	}
	if !this.DelegationRequirement.Equal(that1.DelegationRequirement) {
		return false
	}
	if !this.AirdropFactor.Equal(that1.AirdropFactor) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AirdropFactor != nil {
		{
			size, err := m.AirdropFactor.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAirdrop(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DelegationRequirement != nil {
		{
			size, err := m.DelegationRequirement.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAirdrop(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ExpiryBlocks != 0 {
		i = encodeVarintAirdrop(dAtA, i, uint64(m.ExpiryBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAirdrop(dAtA []byte, offset int, v uint64) int {
	offset -= sovAirdrop(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExpiryBlocks != 0 {
		n += 1 + sovAirdrop(uint64(m.ExpiryBlocks))
	}
	if m.DelegationRequirement != nil {
		l = m.DelegationRequirement.Size()
		n += 1 + l + sovAirdrop(uint64(l))
	}
	if m.AirdropFactor != nil {
		l = m.AirdropFactor.Size()
		n += 1 + l + sovAirdrop(uint64(l))
	}
	return n
}

func sovAirdrop(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAirdrop(x uint64) (n int) {
	return sovAirdrop(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAirdrop
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryBlocks", wireType)
			}
			m.ExpiryBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAirdrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationRequirement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAirdrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAirdrop
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAirdrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DelegationRequirement == nil {
				m.DelegationRequirement = &types.DecProto{}
			}
			if err := m.DelegationRequirement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirdropFactor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAirdrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAirdrop
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAirdrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AirdropFactor == nil {
				m.AirdropFactor = &types.DecProto{}
			}
			if err := m.AirdropFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAirdrop(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAirdrop
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAirdrop(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAirdrop
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAirdrop
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAirdrop
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAirdrop
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAirdrop
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAirdrop
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAirdrop        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAirdrop          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAirdrop = fmt.Errorf("proto: unexpected end of group")
)
