version: 1
build:
  main: ./cmd/ojod
  binary: ojod
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 39000000000000uojo
  mnemonic: entry garbage bike poem grunt negative easily annual miss happy license
    blur false fringe program picture inner tape dismiss eagle include quality drill
    master
- name: bob
  coins:
  - 5500000000000uojo
- name: faucet
  coins:
  - 5500000000000uojo
faucet:
  name: faucet
  coins:
  - 5500000000000uojo
  coins_max:
  - 1000000000uojo
  host: 0.0.0.0:4500
  port: 4500
genesis:
  app_state:
    gov:
      params:
        min_deposit:
          - amount: "100"
            denom: "uojo"
        voting_period: "10s"
        expedited_voting_period: "1s"
    staking:
      params:
        bond_denom: uojo
  consensus:
    params:
        abci:
          vote_extensions_enable_height: "2"
validators:
- name: alice
  bonded: 33500000000000uojo
  app:
    pricefeeder:
      config_path: "./pricefeeder/price-feeder.example.toml"
      enable: true
