name: Build
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - release/**

# This workflow makes amd64 and arm64 binaries for macOS and Linux.
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
    name: ojo ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Setup go
        if: env.GIT_DIFF
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
      - name: Compile
        if: env.GIT_DIFF
        run: |
          go mod download
          cd cmd/ojod
          go build .
      - uses: actions/upload-artifact@v4
        if: env.GIT_DIFF
        with:
          name: ojod-${{ matrix.targetos }}-${{ matrix.arch }}
          path: cmd/ojod/ojod
          retention-days: 1
